theme: jekyll-theme-cayman
show_downloads: true
title: Dwains Lovelace Theme
google_analytics: UA-105338324-4
buttons:
  zip_url: https://github.com/dwainscheeren/lovelace-dwains-theme/releases
  zip_title: Download latest release
  zip_hide: false
  tar_hide: true